apiVersion: v1
kind: ConfigMap
metadata:
  name: swiftbatch-config
  namespace: swiftbatch
data:
  GF_SERVER_ROOT_URL: https://grafana.swiftbatch.abhinash.dev
  MINIO_BROWSER_REDIRECT_URL: https://minio.swiftbatch.abhinash.dev
  MINIO_SERVER_URL: https://storage.swiftbatch.abhinash.dev
  SWIFTBATCH_API_ADDR: ":8080"
  SWIFTBATCH_API_JOBS_CREATE_RATE_LIMIT_BURST: "10"
  SWIFTBATCH_API_JOBS_CREATE_RATE_LIMIT_PER_MINUTE: "30"
  SWIFTBATCH_API_JOBS_RETRY_RATE_LIMIT_BURST: "2"
  SWIFTBATCH_API_JOBS_RETRY_RATE_LIMIT_PER_MINUTE: "6"
  SWIFTBATCH_API_PRESIGN_RATE_LIMIT_BURST: "5"
  SWIFTBATCH_API_PRESIGN_RATE_LIMIT_PER_MINUTE: "20"
  SWIFTBATCH_API_RATE_LIMIT_CLIENT_TTL: 30m
  SWIFTBATCH_API_RATE_LIMIT_ENABLED: "true"
  SWIFTBATCH_ENV: production
  SWIFTBATCH_POSTGRES_DB: swiftbatch
  SWIFTBATCH_POSTGRES_HOST: swiftbatch-postgres
  SWIFTBATCH_POSTGRES_PORT: "5432"
  SWIFTBATCH_POSTGRES_SSLMODE: disable
  SWIFTBATCH_POSTGRES_USER: swiftbatch
  SWIFTBATCH_REDIS_ADDR: swiftbatch-redis:6379
  SWIFTBATCH_REDIS_DB: "0"
  SWIFTBATCH_REDIS_DLQ_KEY: swiftbatch:jobs:dlq
  SWIFTBATCH_REDIS_MAX_RETRIES: "3"
  SWIFTBATCH_REDIS_QUEUE_KEY: swiftbatch:jobs
  SWIFTBATCH_STORAGE_BUCKET: swiftbatch
  SWIFTBATCH_STORAGE_DOWNLOAD_URL_TTL: 30m
  SWIFTBATCH_STORAGE_ENDPOINT: swiftbatch-minio:9000
  SWIFTBATCH_STORAGE_PUBLIC_BASE_URL: https://storage.swiftbatch.abhinash.dev
  SWIFTBATCH_STORAGE_REGION: us-east-1
  SWIFTBATCH_STORAGE_UPLOAD_URL_TTL: 15m
  SWIFTBATCH_STORAGE_USE_SSL: "false"
  SWIFTBATCH_WORKER_CONCURRENCY: "4"
  SWIFTBATCH_WORKER_JOB_TIMEOUT: 2m
  SWIFTBATCH_WORKER_METRICS_ADDR: ":8081"
  SWIFTBATCH_WORKER_POLL_TIMEOUT: 5s
