apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiftbatch-api
  namespace: swiftbatch
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - swiftbatch.abhinash.dev
  rules:
    - host: swiftbatch.abhinash.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiftbatch-api
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiftbatch-minio-object
  namespace: swiftbatch
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - storage.swiftbatch.abhinash.dev
  rules:
    - host: storage.swiftbatch.abhinash.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiftbatch-minio
                port:
                  name: s3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiftbatch-minio-console
  namespace: swiftbatch
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - minio.swiftbatch.abhinash.dev
  rules:
    - host: minio.swiftbatch.abhinash.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiftbatch-minio
                port:
                  name: console
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiftbatch-grafana
  namespace: swiftbatch
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - grafana.swiftbatch.abhinash.dev
  rules:
    - host: grafana.swiftbatch.abhinash.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiftbatch-grafana
                port:
                  name: http
