apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiftbatch-api
  namespace: swiftbatch
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: swiftbatch.abhinash.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiftbatch-api
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiftbatch-minio-object
  namespace: swiftbatch
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: storage.swiftbatch.abhinash.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiftbatch-minio
                port:
                  name: s3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiftbatch-minio-console
  namespace: swiftbatch
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: minio.swiftbatch.abhinash.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiftbatch-minio
                port:
                  name: console
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiftbatch-grafana
  namespace: swiftbatch
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.swiftbatch.abhinash.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiftbatch-grafana
                port:
                  name: http
