apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data
    certificatesResolvers:
      letsencrypt:
        acme:
          email: abhinashjrt22@gmail.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    additionalArguments:
      - --entrypoints.web.http.redirections.entrypoint.to=:443
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
